#version 460 core
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable

#include "../hash.glsl"
#include "../sph/point_hash_grid.glsl"

struct Particle{
    vec4 position;
    vec4 color;
    vec3 velocity;
    float invMass;
};

layout(local_size_x = 1) in;

layout(push_constant) uniform Constants {
    layout(offset = 224)
    vec3 resolution;
    float gridSpacing;
    int pass;
    int numParticles;
};

layout(set = 0, binding = 0) buffer POINTS {
    Particle points[];
};

layout(set = 0, binding = 1) buffer NEAR_BY_KEYS {
    int nearByKeys[8];
};

void main(){
    int id = int(gl_GlobalInvocationID.x);
    getNearByKeys(points[0].position.xyz, gridSpacing, resolution, nearByKeys);
}